"use client";
import { FormEvent, useEffect, useState } from "react";
import styles from "./page.module.css";
type Balance = { outstanding: number; overdue: number; paidThisMonth: number };
type Customer = { id: string; name: string; email: string; balance: number };
type Invoice = { id: string; customerName?: string; amount: number; balance?: number; status: string; dueDate: string };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000";
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
export default function Home() {
  const [token, setToken] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [tenantName, setTenantName] = useState(""); const [registerMode, setRegisterMode] = useState(false); const [submitting, setSubmitting] = useState(false);
  const [balance, setBalance] = useState<Balance | null>(null); const [customers, setCustomers] = useState<Customer[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [error, setError] = useState("");
  async function api<T>(path: string): Promise<T> { const r = await fetch(`${API}${path}`, { headers: { Authorization: `Bearer ${token}` } }); if (!r.ok) throw new Error((await r.json().catch(() => null))?.message ?? "Request failed"); return r.json(); }
  async function load() { try { setError(""); const [b, c, i] = await Promise.all([api<Balance>("/dashboard/balance"), api<Customer[]>("/customers"), api<Invoice[]>("/invoices")]); setBalance(b); setCustomers(c); setInvoices(i); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load dashboard"); } }
  async function authenticate(e: FormEvent) { e.preventDefault(); setError(""); if (registerMode && tenantName.trim().length < 2) { setError("Workspace name must be at least 2 characters."); return; } setSubmitting(true); try { const r = await fetch(`${API}/auth/${registerMode ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(registerMode ? { email, password, tenantName: tenantName.trim() } : { email, password }) }); const data = await r.json().catch(() => null); if (!r.ok) { const message = Array.isArray(data?.message) ? data.message.join(" ") : data?.message; throw new Error(message ?? (registerMode ? "Unable to create account" : "Invalid email or password")); } setToken(data.accessToken ?? data.token); } catch (e) { setError(e instanceof Error ? e.message : (registerMode ? "Unable to create account" : "Unable to sign in")); } finally { setSubmitting(false); } }
  function toggleAuthMode() { setRegisterMode(value => !value); setError(""); }
  // The dashboard load intentionally follows authentication state.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { if (token) void load(); }, [token]);
  if (!token) return <main className={styles.login}><section className={styles.card}><p className={styles.eyebrow}>LEDGERLY</p><h1>{registerMode ? "Create your account." : "Billing, made clear."}</h1><p>{registerMode ? "Start your secure tenant workspace." : "Sign in to your secure tenant dashboard."}</p><form onSubmit={authenticate}>{registerMode && <input aria-label="Workspace name" type="text" placeholder="Workspace name" value={tenantName} onChange={e => setTenantName(e.target.value)} minLength={2} maxLength={100} required />}<input aria-label="Email" type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} required /><input aria-label="Password" type="password" placeholder="Password (8+ characters)" value={password} onChange={e => setPassword(e.target.value)} minLength={8} required /><button type="submit" disabled={submitting}>{submitting ? (registerMode ? "Creating account…" : "Signing in…") : (registerMode ? "Create account" : "Sign in")}</button></form>{error && <p className={styles.error}>{error}</p>}<button type="button" className={styles.toggle} onClick={toggleAuthMode}>{registerMode ? "Already have an account? Sign in" : "Need an account? Create one"}</button></section></main>;
  return <main className={styles.shell}><header><div><p className={styles.eyebrow}>LEDGERLY</p><h1>Overview</h1></div><button className={styles.ghost} onClick={() => setToken("")}>Sign out</button></header>{error && <p className={styles.error}>{error}</p>}<section className={styles.metrics}>{[["Outstanding", balance?.outstanding ?? 0], ["Overdue", balance?.overdue ?? 0], ["Paid this month", balance?.paidThisMonth ?? 0]].map(([label, value]) => <article className={styles.metric} key={label as string}><span>{label}</span><strong>{money(value as number)}</strong></article>)}</section><div className={styles.columns}><section className={styles.panel}><h2>Customers</h2>{customers.map(c => <div className={styles.row} key={c.id}><span><b>{c.name}</b><small>{c.email}</small></span><strong>{money(c.balance)}</strong></div>)}</section><section className={styles.panel}><h2>Recent invoices</h2>{invoices.slice(0, 8).map(i => <div className={styles.row} key={i.id}><span><b>{i.customerName ?? "Customer"}</b><small>{i.status} · due {new Date(i.dueDate).toLocaleDateString()}</small></span><strong>{money(i.balance ?? i.amount)}</strong></div>)}</section></div></main>;
}
