"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./page.module.css";
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000";
const AUTH_TIMEOUT_MS = 20000;
export default function Home() {
  const router = useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [tenantName,setTenantName]=useState(""); const [registerMode,setRegisterMode]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(window.localStorage.getItem("ledgerly_token")) router.replace("/dashboard")},[router]);
  async function authenticate(e: FormEvent){e.preventDefault();setError("");if(registerMode&&tenantName.trim().length<2){setError("Workspace name must be at least 2 characters.");return}setSubmitting(true);const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),AUTH_TIMEOUT_MS);try{const r=await fetch(`${API}/auth/${registerMode?"register":"login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(registerMode?{email,password,tenantName:tenantName.trim()}:{email,password}),signal:controller.signal});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(Array.isArray(d?.message)?d.message.join(" "):d?.message??`Unable to ${registerMode?"create your account":"sign in"}.`);const token=d?.accessToken??d?.token;if(!token)throw new Error("Authentication succeeded but no access token was returned.");window.localStorage.setItem("ledgerly_token",token);window.localStorage.setItem("ledgerly_email",email);router.replace("/dashboard")}catch(v){if(v instanceof DOMException&&v.name==="AbortError")setError("The server took too long to respond. Please try again.");else if(v instanceof TypeError)setError("Unable to reach the server. Check your connection and try again.");else setError(v instanceof Error?v.message:"Something went wrong. Please try again.")}finally{window.clearTimeout(timeout);setSubmitting(false)}}
  return <main className={styles.authPage}><div className={styles.authGlow}/><section className={styles.authCard}><div className={styles.brand}><span className={styles.brandMark}>L</span><span>ledgerly</span></div><div className={styles.authIntro}><span className={styles.kicker}>THE MODERN BILLING DESK</span><h1>{registerMode?"Build your billing workspace.":"Clarity for every invoice."}</h1><p>{registerMode?"Create an account and bring your business finances into focus.":"A calm, powerful home for your invoices, customers, and cash flow."}</p></div><form onSubmit={authenticate} className={styles.authForm}>{registerMode&&<label>Workspace name<input aria-label="Workspace name" value={tenantName} onChange={e=>setTenantName(e.target.value)} minLength={2} required/></label>}<label>Email address<input aria-label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input aria-label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{error&&<p className={styles.formError}>{error}</p>}<button className={styles.primaryButton} type="submit" disabled={submitting}>{submitting?"Please wait…":registerMode?"Create account":"Sign in"}</button></form><button type="button" className={styles.textButton} onClick={()=>{setRegisterMode(v=>!v);setError("")}}>{registerMode?"Already have an account? Sign in":"New to Ledgerly? Create an account"}</button><p className={styles.secureNote}>Your workspace is protected with tenant-isolated access.</p></section></main>;
}
