"use client";
import { FormEvent, useCallback, useEffect, useState } from 'react';
import styles from '../../page.module.css';
import { api, formatMoney } from '../../../lib/api';
type Invoice={id:string;invoiceNumber?:string;customerId:string;customerName?:string;amount:number;balance?:number;status:string;createdAt:string;dueDate:string}; type Customer={id:string;name:string;isArchived:boolean};
const statuses=['ALL','DRAFT','SENT','PAID','OVERDUE','VOID'];
export default function InvoicesPage(){
 const [invoices,setInvoices]=useState<Invoice[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[status,setStatus]=useState('ALL'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState<Invoice|null>(null),[selected,setSelected]=useState<Invoice|null>(null),[saving,setSaving]=useState(false),[customerId,setCustomerId]=useState(''),[amount,setAmount]=useState(''),[dueDate,setDueDate]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [i,c]=await Promise.all([api<Invoice[]>(`/invoices${status==='ALL'?'':`?status=${status}`}`),api<Customer[]>('/customers')]);setInvoices(i);setCustomers(c)}catch(e){setError(e instanceof Error?e.message:'Unable to load invoices.')}finally{setLoading(false)}},[status]);useEffect(()=>{void load()},[load]);
 function openCreate(){setEditing(null);setCustomerId('');setAmount('');setDueDate('');setShowForm(true)} function openEdit(i:Invoice){setEditing(i);setCustomerId(i.customerId);setAmount(String(i.amount));setDueDate(i.dueDate.slice(0,10));setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const body=JSON.stringify({...(editing?{}:{customerId}),amount:Number(amount),dueDate:new Date(`${dueDate}T00:00:00.000Z`).toISOString()});await api(editing?`/invoices/${editing.id}`:'/invoices',{method:editing?'PUT':'POST',body});setShowForm(false);setMessage(editing?'Invoice updated.':'Invoice created.');void load()}catch(e){setError(e instanceof Error?e.message:'Unable to save invoice.')}finally{setSaving(false)}}
 async function action(i:Invoice,action:'send'|'mark-paid'|'mark-overdue'|'void'|'delete'){const label=action==='delete'?'Delete':'Apply '+action.replaceAll('-',' ');if(!window.confirm(label+' '+(i.invoiceNumber||'this invoice')+'?'))return;try{const path=action==='delete'?`/invoices/${i.id}`:`/invoices/${i.id}/${action}`;await api(path,{method:action==='delete'?'DELETE':'POST'});setMessage('Invoice updated.');setSelected(null);void load()}catch(e){setError(e instanceof Error?e.message:'Unable to update invoice.')}}
 const shown=invoices.filter(i=>`${i.invoiceNumber||''} ${i.customerName||''}`.toLowerCase().includes(query.toLowerCase()));
 return <div className={styles.main}><div className={styles.heading}><div><span className={styles.kicker}>LEDGERLY WORKSPACE</span><h1>Invoices<span className={styles.dot}>.</span></h1><p>Create, send, and track invoices for your workspace.</p></div><button className={styles.primaryButton} onClick={openCreate}>New invoice</button></div>{message&&<div className={styles.alert}><span>✓</span><p>{message}</p></div>}{error&&<div className={styles.alert}><span>!</span><div><p>{error}</p><button onClick={()=>void load()}>Try again</button></div></div>}
 {showForm&&<section className={styles.panel}><div className={styles.panelHeader}><div><h2>{editing?'Edit invoice':'Create invoice'}</h2><p>{editing?'Only draft invoice fields can be edited.':'New invoices are created as drafts.'}</p></div></div><form onSubmit={save} className={styles.customerForm}>{!editing&&<select aria-label="Customer" value={customerId} onChange={e=>setCustomerId(e.target.value)} required><option value="">Select customer</option>{customers.filter(c=>!c.isArchived).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<input aria-label="Amount in cents" type="number" min="1" step="1" placeholder="Amount in cents" value={amount} onChange={e=>setAmount(e.target.value)} required/><input aria-label="Due date" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/><button className={styles.primaryButton} disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create invoice'}</button><button type="button" onClick={()=>setShowForm(false)}>Cancel</button></form></section>}
 <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Invoice list</h2><p>{shown.length} invoice{shown.length===1?'':'s'}</p></div><input aria-label="Search invoices" placeholder="Search invoices" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter invoice status" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>{loading?<div className={styles.empty}>Loading invoices…</div>:shown.length?<div className={styles.table}>{shown.map(i=><div className={styles.tableRow} key={i.id}><span><button onClick={()=>setSelected(i)}>{i.invoiceNumber||`Invoice ${i.id.slice(0,6)}`}</button><small>{i.customerName||'Customer'}</small></span><span className={styles.badge}>{i.status}</span><b>{formatMoney(i.balance??i.amount)}</b><small>{new Date(i.dueDate).toLocaleDateString()}</small></div>)}</div>:<div className={styles.empty}><b>No invoices found</b><p>Create an invoice or adjust your filters.</p></div>}</section>
 {selected&&<section className={styles.panel}><div className={styles.panelHeader}><div><h2>{selected.invoiceNumber||'Invoice details'}</h2><p>{selected.customerName||'Customer'} · {selected.status}</p></div><button onClick={()=>setSelected(null)}>Close</button></div><p>Amount: <b>{formatMoney(selected.amount)}</b> · Balance: <b>{formatMoney(selected.balance??selected.amount)}</b></p><p>Issued: {new Date(selected.createdAt).toLocaleDateString()} · Due: {new Date(selected.dueDate).toLocaleDateString()}</p><div className={styles.customerForm}>{selected.status==='DRAFT'&&<><button onClick={()=>openEdit(selected)}>Edit</button><button onClick={()=>void action(selected,'send')}>Send</button><button onClick={()=>void action(selected,'delete')}>Delete</button></>}{(selected.status==='SENT'||selected.status==='OVERDUE')&&<><button onClick={()=>void action(selected,'mark-paid')}>Mark paid</button>{selected.status==='SENT'&&<button onClick={()=>void action(selected,'mark-overdue')}>Mark overdue</button>}<button onClick={()=>void action(selected,'void')}>Void</button></>}</div></section>}
 </div>;
}
